"""conf

Revision ID: 37f6fb105986
Revises: ab28393760f6
Create Date: 2023-10-22 20:46:51.075456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f6fb105986'
down_revision: Union[str, None] = 'ab28393760f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_auth', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_auth', 'avatar')
    # ### end Alembic commands ###
